name: Docker Ztnet Image CI - X86_64/AARCH64 for alpine Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # run it manually
  workflow_dispatch:    

jobs:

  build:

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Build this ztnet Docker image
      run: |
        git clone https://github.com/sinamics/ztnet.git
        cd ztnet
        curl -LO https://gist.githubusercontent.com/shengshampoo/46f573b7c715c7a00e1dde8df35fabc1/raw/b165c28e697157535b0e02aae373d43096f7e27a/ztnet_Dockerfile.alpine
        docker build -f ztnet_Dockerfile.alpine --tag ztnetnn .

    - name: save ztnet docker image 
      run: |
        docker save ztnetnn -o ztnetnn.tar
        xz -e9 ztnetnn.tar
        

    - name: Upload static program
      uses: actions/upload-artifact@v4
      with:
        name: ztnetnn-${{ matrix.os }}
        path: ./ztnetnn.tar.xz
